### ISSUE TITLE
Cleaner templates

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#13]
The Django template engine allows to create a basic template for the package, so it can meld within the base theme the developer is using for it's own template structure.

As a developer I want to have that chance to integrate all my packages in a clean way into my software when I use a Django package.

**Comment by sebastian-code** [comment]
I would dare to say than this is solve @cdvv7788, what do you think?

**Comment by cdvv7788** [comment]
Yeah, i think that is already possible. We use django-qa in a couple projects and we have been able to modify the templates without issues. @jlariza do you agree?

**Comment by jlariza** [comment]
@sebastian-code @cdvv7788 yes, I think right now it is very easy to overwrite the qa templates and use your own. I think this issue is solved. I guess I am closing it, considering we all agree on that.
