### ISSUE TITLE
Recover the reputation system

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#17]
With the migration to a CBV system on the views, we broke the reputation management system, that should be recovered. A "nice to have" setting would be to be able to implement a default set of scores to give credit on the users, but that should be able to be overrided somewhere, so one can change those.

**Comment by cdvv7788** [comment]
@sebastian-code status of this?

**Comment by sebastian-code** [comment]
Is working now, the vote process still needs a better implementation, but the reputation process is working properly.
