### ISSUE TITLE
Wrong accounting of the views

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#21]
How the view has to be calculated and how it has to be accounted for. Actually every time the detail of a question is loaded, a new "view" is added. And plus that, the way the views are being rendered, it sums 3 new views which had no place.

This behaviour is creating wrong statistics on the package.

**Comment by jlariza** [comment]
we could use this package http://django-hitcount.readthedocs.io/en/latest/

It takes into consideration the IP that makes the request, and it is configurable to allow a span of time before that IP may hit another view.
I have used it before and it works fine; and it is very easy to integrate with an existing project

**Comment by cdvv7788** [comment]
Released to pypi on version 0.1.1.

**Comment by sebastian-code** [comment]
It actually improved the hit count on the question a lot, but still there is a way to cheat it. If you do the view in a fresh _private session tab_ on your browser, you can register a new visit every time; I suppose than it also applies to your regular browser if you delete your cookies and navigation history. I don't see people doing it, but that's perhaps how the package works.

**Comment by cdvv7788** [comment]
That's expected behavior. Another option would be limiting views to logged in users, but we should leave that to the package users. We could add a setting for that.
