### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#22]
Swapps uses fondly CodeShip, but there is also space to consider Travis CI and at least coverage integration with Coveralls I/O, Requirements I/O would be also nice to have.

**Comment by cdvv7788** [comment]
We added travis, working on coveralls.

**Comment by jlariza** [comment]
@sebastian-code @cdvv7788 coveralls is working on this repo. What else do we need for this task? read the docs maybe?

**Comment by cdvv7788** [comment]
@jlariza https://requires.io/ and yeah, writing some docs and moving them over read the docs would be nice too.

**Comment by sebastian-code** [comment]
Besides the documentation on Read the Docs, is everything in place? What do you think?

**Comment by cdvv7788** [comment]
Yeah, i think so.
