### ISSUE TITLE
Current feature set (was: is this project using Django comments?)

### ISSUE THREAD

**Issue by jjmontesl** [swappsco/django-qa#23]
Does this project use Django Comments (https://django-contrib-comments.readthedocs.io/en/latest/)?

**Comment by sebastian-code** [comment]
Hi @jjmontesl!

No, this package is not using that package, our original intent was to implement the leaner pluggable app possible, so you are not going to have issues for that, as you can see, we even implemented our own set of validation mixins on authentication to avoid to install something like django-braces.

The comments functionality is actually really lean and does the minimum we envisioned in the beginning. Why do you ask?

**Comment by jjmontesl** [comment]
Just curious. I wish to integrate Q&A functionality in an app (cubesviewer) and I'm researching alternatives. My first thought was to implement Q&A myself on top of django-comments, but ideally something more featureful would exist.

Could you please comment on current support for the following features?

* Integration with Django authentication
* Comments on questions and answers
* Support for anonymous questions and answers and comments
* Full REST support
* Tag support
* Score/reputation system
* Moderation options

**Comment by sebastian-code** [comment]
Hi @jjmontesl 

Well, we have implemented django-qa a few times, and the actual state of development is in sync with those needs, but we keep developing and improving the package.

To answer your specific questions:

- The package is integrated with the framework authentication process, right now the package defines an user profile linked to Django's user model, this models was created to contain information related to the user's activities inside the package functionalities.
- It has comments on questions and answers.
- It has no support for anonymous questions nor answers or comments.
- It has not REST support yet.
- It has tagging support through django-taggit.
- It has a basic implementation for score and reputation records.
- The package has no moderation options yet.

**Comment by jjmontesl** [comment]
Thank you for the summary. Sounds good enough, I'll try with your package first.

I may miss REST support, as I'm not sure how I'll integrate user interface yet. We'll see.

Thanks for your work on a very-much needed library, imho.

**Comment by jjmontesl** [comment]
As a side note, I was asking about django-comments because imho if this project was bujilt on django-comments, one would feel a little more "free to try it". Same goes for tags, where you already use django-taggit :-).
