### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jjmontesl** [swappsco/django-qa#24]
I'm missing some documentation on the features and quickstart with django-qa. Would it be possible to get some heads up docs?

**Comment by sebastian-code** [comment]
Hi @jjmontesl!

Actually we haven't worked too much on the docs, but we will, it hasn't been a priority for us but that task is on our ToDo list.

**Comment by cdvv7788** [comment]
I can work on this tomorrow. Meanwhile you can just install it with "pip install django-qa" and add "qa" to your installed apps. Add the urls to your main urls file and run migrations. That's about it.
We are still deciding on some things tho, so the api and some behaviours may change between versions until we are ready for the first stable release.
About the features, for now, we support the core of a qa app: creation of questions, answers, votes and comments for both questions and answers, count of views, user profiles, basic support for scores ala SO, etc.

**Comment by cdvv7788** [comment]
I updated the README. @sebastian-code can you give it a quick review/cleanup? https://github.com/swappsco/django-qa/blob/develop/README.md

**Comment by sebastian-code** [comment]
The wording is just fine @cdvv7788, I added a little bit of information about the core functionalities, based on the list created to answer #23

**Comment by jjmontesl** [comment]
Kudos :100:
