### ISSUE TITLE
A guide to integrating their static files should also be included in the readme document.

### ISSUE THREAD

**Issue by NicolasJupiter** [swappsco/django-qa#29]

**Comment by cdvv7788** [comment]
I think that we don't use anything out of the standard for the staticfiles. Can you please explain what issue are you having with static files or what needs to be explained? You are welcome to send a pull request too.

**Comment by cdvv7788** [comment]
I don't know if it is related, but after removing django-bootstrap3 as a project dependency bootstrap was not loading. I added it to the base.html and it seems to be working again.
I also added a comment to the readme. I am not a fan of CDNs, but it is up to the user to provide their own templates, if they don't like some things about the default ones.

I will release these changes today.

**Comment by cdvv7788** [comment]
https://github.com/swappsco/django-qa/releases/tag/0.0.32
