### ISSUE TITLE
Fix readme formatting on pypi

### ISSUE THREAD

**Issue by cdvv7788** [swappsco/django-qa#30]
Pypi requires rst to work. There are 2 options:

- Change our current README.md to rst format (should be easy)
- Use: https://coderwall.com/p/qawuyq/use-markdown-readme-s-in-python-modules
The second approach can work, but i don't see a reason to stick with md as github works with rst too.

**Comment by sebastian-code** [comment]
Solve with c98d4cf6f27e0ec80b8f2d4c8b1ed4baad98a6c5
