### ISSUE TITLE
Lack of proper documentation

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#33]
Right now the package lacks documentation. Part of it because there is no clear path to what is needed as documentation for the project.

**Comment by cdvv7788** [comment]
@sebastian-code Should we create a basic documentation in RTD?

**Comment by sebastian-code** [comment]
I'm not sure about it @cdvv7788, is the package that complex than we need something of the likes of RTD? is there any other alternative? Obviously, we can go with that kind of documentation, and evolve it with the package. Perhaps we should do it.

**Comment by sebastian-code** [comment]
Thinking it through, I would say than we should go with it. How does that works?

**Comment by sebastian-code** [comment]
It's already starting on the develop branch, but still lacks proper everything

**Comment by cdvv7788** [comment]
Thanks @sebastian-code.
