### ISSUE TITLE
Move settings to dictionary

### ISSUE THREAD

**Issue by cdvv7788** [swappsco/django-qa#36]
All package settings should be inside of a dictionary.

**Comment by sebastian-code** [comment]
Some pointers to implement or to have in mind for development:

Upvote/Downvote Question -> Creator
Upvote/Downvote Answer -> Creator
Upvote/Downvote QuestionComments -> Creator
Upvote/Downvote AnswerComments -> Creator
Accepted Answer -> Creator
Downvoting Question -> Voter
Downvoting Answer -> Voter
Downvoting QuestionComment -> Voter
Downvoting QuestionAnswer -> Voter

Need to lock rows before updating to avoid race conditions
Use points field in qa-profile to store total reputation
Create user profile model methods
Assume all values not in settings as 0

**Comment by sebastian-code** [comment]
Almost done, the functionality still lacks the Vote part, but the other activities are already affecting the reputation in a proper way.

**Comment by sebastian-code** [comment]
This is done with the latest release. Closing now.
