### ISSUE TITLE
Add setting to configure hitcount

### ISSUE THREAD

**Issue by cdvv7788** [swappsco/django-qa#38]
It should allow me to select if i want to count the hits from any user or just the logged in ones.

**Comment by sebastian-code** [comment]
Shouldn't this work around the hitcount package?

**Comment by cdvv7788** [comment]
@sebastian-code it is, and should be implemented already. Please verify and close.

**Comment by sebastian-code** [comment]
According to the documentation, this is done inside the view, the proper way to do it is to inherit from LoginRequiredMixin inside the DetailView.

**Comment by sebastian-code** [comment]
Looking into the code, the only thing there is room to implement is to override the `count_hit` variable inside the `QuestionDetailView` through the `QA_SETTINGS` dictionary inside the settings file, which is going to default to `True`.

**Comment by cdvv7788** [comment]
If we are requiring the package, i don't see a good reason to avoid this. If the user definitely wants to disable it, he can subclass it.

**Comment by sebastian-code** [comment]
Fixed 9cc46def3e44b826b65ed8394afbe31f53baf13f
