### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by vikrampanwar** [swappsco/django-qa#39]
plz provide how to use this app once it is installed.
i found qa files in my libraries of the project but don't know what to import and what functions to call to get my work done. plz provide ASAP.

**Comment by sebastian-code** [comment]
Hi @vikrampanwar this is the actual documentation https://django-qa.readthedocs.io/en/latest/ there you can find instructions to install and implement the package; does it solve your requirement? do you need more help?

**Comment by sebastian-code** [comment]
Closing unless there is additional requirements.
