### ISSUE TITLE
bug add new question

### ISSUE THREAD

**Issue by remydev** [swappsco/django-qa#40]
Hello,
I just tryed to install django-qa but i have got the folowing error.

I tried it on a new django install,
`pip install django-qa`
and i simply add 

`INSTALLED_APPS = (
...
'qa',
'taggit',
'hitcount',
...
)`

TemplateDoesNotExist at /en/admin/qa/question/add/
django_markdown/editor_init.html

Request Method:	GET
Request URL:	http://192.168.122.150:8000/en/admin/qa/question/add/
Django Version:	1.8.18
Exception Type:	TemplateDoesNotExist
Exception Value:	
django_markdown/editor_init.html
Exception Location:	/root/env/decattitude/lib/python3.5/site-packages/django/template/loader.py in get_template, line 46
Python Executable:	/root/env/decattitude/bin/python
Python Version:	3.5.3
Python Path:	
['/root/projects/qa_question',
 '/root/env/decattitude/lib/python35.zip',
 '/root/env/decattitude/lib/python3.5',
 '/root/env/decattitude/lib/python3.5/plat-x86_64-linux-gnu',
 '/root/env/decattitude/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/root/env/decattitude/lib/python3.5/site-packages']
Server time:	Tue, 5 Sep 2017 09:32:54 +0200

Template-loader postmortem

Django tried loading these templates, in this order:
Using loader django.template.loaders.filesystem.Loader:
/root/projects/qa_question/qa_question/templates/django_markdown/editor_init.html (File does not exist)
Using loader django.template.loaders.app_directories.Loader:
/root/env/decattitude/lib/python3.5/site-packages/djangocms_admin_style/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/django/contrib/auth/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/django/contrib/admin/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/django/contrib/sitemaps/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/cms/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/menus/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/treebeard/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/djangocms_text_ckeditor/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/filer/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/djangocms_column/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/djangocms_link/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/cmsplugin_filer_file/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/cmsplugin_filer_folder/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/cmsplugin_filer_image/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/djangocms_style/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/djangocms_snippet/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/djangocms_googlemap/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/djangocms_video/templates/django_markdown/editor_init.html (File does not exist)
/root/projects/qa_question/qa_question/templates/django_markdown/editor_init.html (File does not exist)
/root/env/decattitude/lib/python3.5/site-packages/qa/templates/django_markdown/editor_init.html (File does not exist)
Using loader django.template.loaders.eggs.Loader:

## Error during template rendering

In template /root/env/decattitude/lib/python3.5/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
django_markdown/editor_init.html

9	            {% for field in line %}
10	                <div{% if not line.fields|length_is:'1' %} class="field-box{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %} class="checkbox-row"{% endif %}>
11	                    {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
12	                    {% if field.is_checkbox %}
13	                        {{ field.field }}{{ field.label_tag }}
14	                    {% else %}
15	                        {{ field.label_tag }}
16	                        {% if field.is_readonly %}
17	                            <p>{{ field.contents }}</p>
18	                        {% else %}
19	
                                  
     ###  {{ field.field }}
      

      
20	                        {% endif %}
21	                    {% endif %}
22	                    {% if field.field.help_text %}
23	                        <p class="help">{{ field.field.help_text|safe }}</p>
24	                    {% endif %}
25	                </div>
26	            {% endfor %}
27	        </div>
28	    {% endfor %}
29	</fieldset>

**Comment by sebastian-code** [comment]
Hi @remydev from the stack trace I can see than your issue is with the package django-markdown-app, it looks like is not installed, did you installed the package manually? if so, did you installed the requirements? did you use pip to install the package?

**Comment by remydev** [comment]
thanks to replay ;)

yes i do it with pip ...

(decattitude) root@debian:~/projects# pip install django-markdown-app==0.9.2
Requirement already satisfied: django-markdown-app==0.9.2 in /root/env/decattitude/lib/python3.5/site-packages
Requirement already satisfied: markdown>=2.6.7 in /root/env/decattitude/lib/python3.5/site-packages (from django-markdown-app==0.9.2)
Requirement already satisfied: Django<=1.11,>=1.8 in /root/env/decattitude/lib/python3.5/site-packages (from django-markdown-app==0.9.2)

**Comment by sebastian-code** [comment]
Hi @remydev I have been trying to replicate the error but I'm unable to achieve it. Is there additional information you can provide about your issue?

**Comment by remydev** [comment]
I tried with a fresh install, but I'm not good enough to understand the problem, I have the same result again.
I do not know what information can help, I do it with a simple django and here with django cms same resurl

root@debian:~# virtualenv env/qa2 -p /usr/bin/python3.5
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /root/env/qa2/bin/python3.5
Also creating executable in /root/env/qa2/bin/python
Installing setuptools, pip, wheel...done.
root@debian:~# source env/qa2/bin/activate
(qa2) root@debian:~# cd qa
qa/  qa2/ 
(qa2) root@debian:~# cd qa2/
(qa2) root@debian:~/qa2# mkdir qa2
(qa2) root@debian:~/qa2# cd qa2/
(failed reverse-i-search)`': git clone https://github.com/swappsco/^Cango-qa.git
(qa2) root@debian:~/qa2/qa2# pip3 install djangocms-installer
Collecting djangocms-installer
  Using cached djangocms_installer-0.9.7-py2.py3-none-any.whl
Collecting argparse (from djangocms-installer)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: pip in /root/env/qa2/lib/python3.5/site-packages (from djangocms-installer)
Collecting six (from djangocms-installer)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting dj-database-url>=0.4 (from djangocms-installer)
  Using cached dj_database_url-0.4.2-py2.py3-none-any.whl
Collecting tzlocal (from djangocms-installer)
Collecting pytz (from tzlocal->djangocms-installer)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Installing collected packages: argparse, six, dj-database-url, pytz, tzlocal, djangocms-installer
Successfully installed argparse-1.4.0 dj-database-url-0.4.2 djangocms-installer-0.9.7 pytz-2017.2 six-1.10.0 tzlocal-1.4
(qa2) root@debian:~/qa2/qa2# djangocms -p . qa2
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
Operations to perform:
  Synchronize unmigrated apps: treebeard, qa2, messages, djangocms_admin_style, staticfiles, sekizai, sitemaps, cmsplugin_filer_utils
  Apply all migrations: auth, djangocms_text_ckeditor, cms, djangocms_column, cmsplugin_filer_folder, djangocms_snippet, cmsplugin_filer_image, admin, djangocms_video, cmsplugin_filer_file, filer, menus, sessions, djangocms_googlemap, sites, djangocms_link, easy_thumbnails, contenttypes, djangocms_style
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207... OK
  Applying cms.0013_urlconfrevision... OK
  Applying cms.0014_auto_20160404_1908... OK
  Applying cms.0015_auto_20160421_0000... OK
  Applying cms.0016_auto_20160608_1535... OK
  Applying filer.0001_initial... OK
  Applying cmsplugin_filer_file.0001_initial... OK
  Applying cmsplugin_filer_file.0002_auto_20160112_1617... OK
  Applying cmsplugin_filer_file.0003_filerfile_link_attributes... OK
  Applying cmsplugin_filer_file.0004_auto_20160705_1334... OK
  Applying cmsplugin_filer_file.0005_auto_20160713_1853... OK
  Applying cmsplugin_filer_folder.0001_initial... OK
  Applying cmsplugin_filer_folder.0002_auto_20160113_1318... OK
  Applying cmsplugin_filer_folder.0003_auto_20160713_1853... OK
  Applying filer.0002_auto_20150606_2003... OK
  Applying filer.0003_thumbnailoption... OK
  Applying cmsplugin_filer_image.0001_initial... OK
  Applying cmsplugin_filer_image.0002_auto_20160108_1708... OK
  Applying cmsplugin_filer_image.0003_mv_thumbnail_option_to_filer_20160119_1720... OK
  Applying cmsplugin_filer_image.0004_auto_20160120_0950... OK
  Applying cmsplugin_filer_image.0005_auto_20160224_1457... OK
  Applying cmsplugin_filer_image.0006_auto_20160427_1438... OK
  Applying cmsplugin_filer_image.0007_filerimage_link_attributes... OK
  Applying cmsplugin_filer_image.0008_auto_20160705_1334... OK
  Applying cmsplugin_filer_image.0009_auto_20160713_1853... OK
  Applying djangocms_column.0001_initial... OK
  Applying djangocms_column.0002_auto_20160915_0818... OK
  Applying filer.0004_auto_20160328_1434... OK
  Applying filer.0005_auto_20160623_1425... OK
  Applying filer.0006_auto_20160623_1627... OK
  Applying filer.0007_auto_20161016_1055... OK
  Applying djangocms_googlemap.0001_initial... OK
  Applying djangocms_googlemap.0002_auto_20160622_1031... OK
  Applying djangocms_googlemap.0003_auto_20160825_1829... OK
  Applying djangocms_googlemap.0004_adapted_fields... OK
  Applying djangocms_googlemap.0005_create_nested_plugins... OK
  Applying djangocms_googlemap.0006_remove_fields... OK
  Applying djangocms_googlemap.0007_reset_null_values... OK
  Applying djangocms_googlemap.0008_removed_null_fields... OK
  Applying djangocms_googlemap.0009_googlemapmarker_icon... OK
  Applying djangocms_link.0001_initial... OK
  Applying djangocms_link.0002_auto_20140929_1705... OK
  Applying djangocms_link.0003_auto_20150212_1310... OK
  Applying djangocms_link.0004_auto_20150708_1133... OK
  Applying djangocms_link.0005_auto_20151003_1710... OK
  Applying djangocms_link.0006_remove_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_link.0007_set_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_link.0008_link_attributes... OK
  Applying djangocms_link.0009_auto_20160705_1344... OK
  Applying djangocms_link.0010_adapted_fields... OK
  Applying djangocms_link.0011_fixed_null_values... OK
  Applying djangocms_link.0012_removed_null... OK
  Applying djangocms_link.0013_fix_hostname... OK
  Applying djangocms_snippet.0001_initial... OK
  Applying djangocms_snippet.0002_snippet_slug... OK
  Applying djangocms_snippet.0003_auto_data_fill_slug... OK
  Applying djangocms_snippet.0004_auto_alter_slug_unique... OK
  Applying djangocms_snippet.0005_set_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_snippet.0006_auto_20160831_0729... OK
  Applying djangocms_snippet.0007_auto_alter_template_helptext... OK
  Applying djangocms_style.0001_initial... OK
  Applying djangocms_style.0002_set_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_style.0003_adapted_fields... OK
  Applying djangocms_style.0004_use_positive_small_integer_field... OK
  Applying djangocms_style.0005_reset_null_values... OK
  Applying djangocms_style.0006_removed_null_fields... OK
  Applying djangocms_style.0007_style_template... OK
  Applying djangocms_text_ckeditor.0001_initial... OK
  Applying djangocms_text_ckeditor.0002_remove_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_text_ckeditor.0003_set_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_text_ckeditor.0004_auto_20160706_1339... OK
  Applying djangocms_video.0001_initial... OK
  Applying djangocms_video.0002_set_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_video.0003_field_adaptions... OK
  Applying djangocms_video.0004_move_to_attributes... OK
  Applying djangocms_video.0005_migrate_to_filer... OK
  Applying djangocms_video.0006_field_adaptions... OK
  Applying djangocms_video.0007_create_nested_plugin... OK
  Applying djangocms_video.0008_reset_null_values... OK
  Applying djangocms_video.0009_removed_null_values... OK
  Applying easy_thumbnails.0001_initial... OK
  Applying easy_thumbnails.0002_thumbnaildimensions... OK
  Applying menus.0001_initial... OK
  Applying sessions.0001_initial... OK
Creating admin user
All done!
Get into "/root/qa2/qa2" directory and type "python manage.py runserver" to start your project
(qa2) root@debian:~/qa2/qa2# cd qa2/
(qa2) root@debian:~/qa2/qa2/qa2# vim settings.py 
(qa2) root@debian:~/qa2/qa2/qa2# pip3 install django-annoying==0.10.3
Collecting django-annoying==0.10.3
Installing collected packages: django-annoying
Successfully installed django-annoying-0.10.3
(qa2) root@debian:~/qa2/qa2/qa2# pip3 install django-markdown-app==0.9.2
Collecting django-markdown-app==0.9.2
  Using cached django_markdown_app-0.9.2-py2.py3-none-any.whl
Requirement already satisfied: Django<=1.11,>=1.8 in /root/env/qa2/lib/python3.5/site-packages (from django-markdown-app==0.9.2)
Collecting markdown>=2.6.7 (from django-markdown-app==0.9.2)
Installing collected packages: markdown, django-markdown-app
Successfully installed django-markdown-app-0.9.2 markdown-2.6.9
(qa2) root@debian:~/qa2/qa2/qa2# pip3 install django-taggit==0.22.1
Collecting django-taggit==0.22.1
  Using cached django_taggit-0.22.1-py2.py3-none-any.whl
Installing collected packages: django-taggit
Successfully installed django-taggit-0.22.1
(qa2) root@debian:~/qa2/qa2/qa2# pip3 install pytz==2017.2
Requirement already satisfied: pytz==2017.2 in /root/env/qa2/lib/python3.5/site-packages
(qa2) root@debian:~/qa2/qa2/qa2# pip3 install django-hitcount==1.2.2
Collecting django-hitcount==1.2.2
  Using cached django_hitcount-1.2.2-py2.py3-none-any.whl
Installing collected packages: django-hitcount
Successfully installed django-hitcount-1.2.2
(qa2) root@debian:~/qa2/qa2/qa2# cd ..
(qa2) root@debian:~/qa2/qa2# pip3 install django-qa
Collecting django-qa
Collecting django-taggit==0.21.3 (from django-qa)
  Using cached django_taggit-0.21.3-py2.py3-none-any.whl
Requirement already satisfied: django-hitcount==1.2.2 in /root/env/qa2/lib/python3.5/site-packages (from django-qa)
Requirement already satisfied: django-annoying==0.10.3 in /root/env/qa2/lib/python3.5/site-packages (from django-qa)
Collecting pytz==2016.10 (from django-qa)
  Using cached pytz-2016.10-py2.py3-none-any.whl
Collecting django-markdown-app==0.9.0 (from django-qa)
Requirement already satisfied: markdown in /root/env/qa2/lib/python3.5/site-packages (from django-markdown-app==0.9.0->django-qa)
Requirement already satisfied: django in /root/env/qa2/lib/python3.5/site-packages (from django-markdown-app==0.9.0->django-qa)
Installing collected packages: django-taggit, pytz, django-markdown-app, django-qa
  Found existing installation: django-taggit 0.22.1
    Uninstalling django-taggit-0.22.1:
      Successfully uninstalled django-taggit-0.22.1
  Found existing installation: pytz 2017.2
    Uninstalling pytz-2017.2:
      Successfully uninstalled pytz-2017.2
  Found existing installation: django-markdown-app 0.9.2
    Uninstalling django-markdown-app-0.9.2:
      Successfully uninstalled django-markdown-app-0.9.2
Successfully installed django-markdown-app-0.9.0 django-qa-0.1.1 django-taggit-0.21.3 pytz-2016.10
(qa2) root@debian:~/qa2/qa2# python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: sekizai, treebeard, messages, qa2, cmsplugin_filer_utils, django_markdown, sitemaps, staticfiles, djangocms_admin_style
  Apply all migrations: taggit, djangocms_googlemap, djangocms_video, djangocms_column, easy_thumbnails, filer, admin, hitcount, cmsplugin_filer_folder, qa, djangocms_snippet, cmsplugin_filer_file, menus, sessions, djangocms_link, auth, sites, cms, djangocms_text_ckeditor, cmsplugin_filer_image, djangocms_style, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying hitcount.0001_initial... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying qa.0001_initial... OK
  Applying qa.0002_auto_20160412_1336... OK
  Applying qa.0003_auto_20160414_1413... OK
  Applying qa.0004_answer_updated... OK
  Applying qa.0005_auto_20160519_1057... OK
  Applying qa.0006_question_total_points... OK
  Applying qa.0007_answer_total_points... OK
  Applying qa.0008_auto_20160719_0729... OK
  Applying qa.0009_auto_20160919_1528... OK
  Applying qa.0010_auto_20160919_2033... OK
  Applying qa.0011_question_slug... OK
  Applying qa.0012_remove_question_views... OK
(qa2) root@debian:~/qa2/qa2# python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
September 05, 2017 - 22:02:35
Django version 1.8.18, using settings 'qa2.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[05/Sep/2017 22:03:16] "GET /admin/ HTTP/1.1" 302 0
[05/Sep/2017 22:03:16] "GET /en/admin/ HTTP/1.1" 302 0
[05/Sep/2017 22:03:16] "GET /en/admin/login/?next=/en/admin/ HTTP/1.1" 200 2755
[05/Sep/2017 22:03:18] "POST /en/admin/login/?next=/en/admin/ HTTP/1.1" 302 0
[05/Sep/2017 22:03:18] "GET /en/admin/ HTTP/1.1" 200 14357
[05/Sep/2017 22:03:23] "GET /en/admin/qa/question/add/ HTTP/1.1" 500 335039

**Comment by cdvv7788** [comment]
@remydev Does the sample project run for you? Clone the repo, open test_project, install requirements and run "python manage.py runserver".

**Comment by remydev** [comment]
Ok it's works with the clone, when i start the test_project.
I will try to understand why and come back
thanks
