### ISSUE TITLE
Dependency problem, if installed from pip

### ISSUE THREAD

**Issue by Postroutine** [swappsco/django-qa#46]
If I try to install `django-qa` from pip, I get a dependency that can't be satisfied.
The  dependency is `django-markdown-app`.  `django-qa` require `django-markdown-app` at version  0.9.2 but the only available versions are 0.8.5, 0.8.5.1, 0.9.3.1, 0.9.4 and 0.9.4.1.

I launched pip on:
- Virtualenv
- Python 3.6.4
- Fedora GNU/Linux 27

Command launched:
```
pip install django-qa
```

Result:
```
Collecting django-qa
  Using cached django-qa-0.9.1.tar.gz
Collecting django-annoying==0.10.3 (from django-qa)
  Using cached django_annoying-0.10.3-py2.py3-none-any.whl
Collecting django-markdown-app==0.9.2 (from django-qa)
  Could not find a version that satisfies the requirement django-markdown-app==0.9.2 (from django-qa) (from versions: 0.8.5, 0.8.5.1, 0.9.3.1, 0.9.4, 0.9.4.1)
No matching distribution found for django-markdown-app==0.9.2 (from django-qa)
```

**Comment by sebastian-code** [comment]
Solved. Closing

**Comment by Postroutine** [comment]
That was quick.
Thanks. 

How many time before available on PIP?

**Comment by sebastian-code** [comment]
Good question, I'm ashamed to say this, but I don't know, I'm not that aware of how long it takes. I can guess it takes around an hour.

**Comment by Postroutine** [comment]
Who manage the package on `pip`?

**Comment by Postroutine** [comment]
I check the `0.9.4.1` release and the `setup.py` file still require `django-markdown-app` at version 0.9.2.
Bug not fixed. :(

**Comment by Postroutine** [comment]
I propose a PR to avoid this problem in the future: https://github.com/swappsco/django-qa/pull/48/

**Comment by nickkfwong** [comment]
Hi, i have exact the same problem. I guess the latest update is still not available from pip?

Is there anyway to setup before it is properly updated on the packaging repo?

**Comment by Postroutine** [comment]
@nickkfwong 
```
pip install https://github.com/swappsco/django-qa/archive/0.9.4.4.tar.gz
```
