### ISSUE TITLE
[Feature Request] Ability to mark which answer resolve the question

### ISSUE THREAD

**Issue by Postroutine** [swappsco/django-qa#50]
Actually, you can mark a question as resolved. But you can't say which answer resolve the question.

It would be useful if you can mark and show which answer resolve the question.

**Comment by Postroutine** [comment]
I see you have started by creating a view named `AnswerQuestionView`, but it's not used on any template. What is his status?

**Comment by cdvv7788** [comment]
Oh really? The user should have the possibility of knowing which question was marked as an answer. I will check this and the PR. Thanks!

**Comment by cdvv7788** [comment]
Added a couple things to PR and closed it. Marking the answer as the accepted one, should not close the question. I added a button to the question so the owner can close it if he wants to. Thanks for the PR.
