### ISSUE TITLE
In all views: head elements (html) in wrong place

### ISSUE THREAD

**Issue by Postroutine** [swappsco/django-qa#53]
In all views, the HTML head elements are inside the body.

This is what I get at the top of the HTML:
```html
<div class="topbar"></div>
<div class="container">
<title>Simple QA</title>
<link rel="icon" type="image/png" href="static/qa/icon.ico">
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


<link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/static/css/qa.css" rel="stylesheet"/>

<div class="page-header">
```

No <head> part.

**Comment by cdvv7788** [comment]
I have to review this. It may be a documentation issue because if I am not wrong this is meant to be included in a parent template. Again, have to review. Will have you an answer soon. Sorry for the delay.

**Comment by cdvv7788** [comment]
Merged. You were right. Even if the base template is going to be overriden, it should not be incomplete. Thanks for the PR!
