### ISSUE TITLE
Load fonts, JS and CSS locally

### ISSUE THREAD

**Issue by ghost** [swappsco/django-qa#54]
In order to respect private life of users and independence of the application, it would be better to load all CSS, JS, fonts and other locally instead of using external url.

**Comment by sebastian-code** [comment]
Could you elaborate?

**Comment by Postroutine** [comment]
[Google Fonts](https://protonmail.uservoice.com/forums/284483-feedback/suggestions/10401618-stop-using-google-fonts-which-track-users-browsi) and  BootstrapCDN are known for tracking visitors.

And depending on external services for providing some parts of the website is not a good idea for the independence of the application. If Google or Bootstrap fail, the QA application too.

**Comment by Postroutine** [comment]
PS: I can work on that. ;)

**Comment by cdvv7788** [comment]
Well, I think that is mainly a documentation issue. What we want is an application that can be embedded into a site without forcing them to use our templates. If the end user is not using bootstrap or google fonts, those files won't stay around.
Does that make sense? @Postroutine

**Comment by cdvv7788** [comment]
The issue with this is that adding an internal javascript dependency to the package will add it when the user runs collectstatic, thing that I want to avoid. If the user already uses a bootstrap he will have 2 different bootstrap files simultaneously.
What I propose for this, is moving the requirements into their own block, and keeping the current dependencies by default. With that, the user will have the freedom to switch them for the ones that are already in the project.
