### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by TheFoolishKumar** [swappsco/django-qa#57]
`pip install django-qa` results in an error saying,
Could not find a version that satisfies the requirement django-markdown-app==0.9.2 (from django-qa) (from versions: 0.8.5, 0.8.5.1, 0.9.3.1, 0.9.4, 0.9.4.1)
No matching distribution found for django-markdown-app==0.9.2 (from django-qa)

**Comment by sebastian-code** [comment]
Please take a look at #47
