### ISSUE TITLE
Voting views calling a wrong instance

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#6]
The vote view (both for up vote and down vote) is not working properly, because it is calling directly the user name and not an instance throwing this error: `ValueError: Cannot query "maestro": Must be "User" instance.`

**Comment by sebastian-code** [comment]
Solved, closing it.

**Comment by sebastian-code** [comment]
Reopening because still failing.

**Comment by cdvv7788** [comment]
I fixed this already. Should be working now.
