### ISSUE TITLE
Migrate repo to a non-fork

### ISSUE THREAD

**Issue by cdvv7788** [swappsco/django-qa#65]
Having this repo being a fork is not useful in any way. The parent repository is probably dead and does not serve any purpose. We can change this repository to be the parent one, but that will mean that all the stars/forks, etc will be lost.
Is that worth it?

**Comment by sebastian-code** [comment]
The relationship with the parent repository has no real effect on the package, and deleting the repository I guess will hurt at least at some level the package _fame_ (is that a thing?).

My opinion? Is not worth it.
