### ISSUE TITLE
Fix url routing

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#8]
The app has no url routing implemented properly, right now the urls file is inside the example proyect, so the app lacks urls in case is used outside that scope.

**Comment by cdvv7788** [comment]
We moved this already. App only has the urls it does require. Is there something we are missing?

**Comment by sebastian-code** [comment]
Yes, the URLConf for the django-markdown package, that URL persist on the test project urls file. If I try to move it to the package urls file, it broke the question registering flow.

**Comment by jlariza** [comment]
I think this has already been solved. I am closing this issue.
