### ISSUE TITLE
Implement testing

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#9]
Implement test on the app

**Comment by cdvv7788** [comment]
What does we need to consider this complete? We already have some test structure for the app and a couple tests implemented. We are still missing travis, but that can be done on a separate issue.

**Comment by sebastian-code** [comment]
I would say than coverage > 95 would be fine, what do you think?

**Comment by cdvv7788** [comment]
90 should be enough, but we can try 95.

**Comment by cdvv7788** [comment]
Also, @jlariza added travis to the repo. We are still working on https://github.com/swappsco/django-qa/issues/22

**Comment by sebastian-code** [comment]
Now we are at 91% did we achieve the goal @cdvv7788 or do we chase the 95%?

**Comment by cdvv7788** [comment]
I think 90% is good enough for now. We can try going for 95%, but keep 90 as the minimum.
